services:
  mongo:
    image: mongo:8.3
    container_name: reactive-rag-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: reactive_rag
    volumes:
      - type: bind
        source: ${MONGO_DATA_PATH:-./.docker/mongo-data}
        target: /data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: reactive-rag-mongo-express
    depends_on:
      - mongo
    ports:
      - "8086:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: "false"

  qdrant:
    image: qdrant/qdrant:v1.19.0
    container_name: reactive-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - type: bind
        source: ${QDRANT_DATA_PATH:-./.docker/qdrant-storage}
        target: /qdrant/storage
