spring:
  mongodb:
    uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/reactive_rag?authSource=admin}

file-processor:
  dataset-path: ${DATASET_PATH:./data/dataset.txt}
  dataset-id: ${DATASET_ID:local-dataset}
  chunk-index: ${CHUNK_INDEX:0}
  start-byte-inclusive: ${START_BYTE_INCLUSIVE:0}
  end-byte-exclusive: ${END_BYTE_EXCLUSIVE:1048576}
  max-line-length-bytes: ${MAX_LINE_LENGTH_BYTES:1048576}
  buffer-size-bytes: ${BUFFER_SIZE_BYTES:4194304}
  rag-chunk-max-text-length-characters: ${RAG_CHUNK_MAX_TEXT_LENGTH_CHARACTERS:8000}
  rag-chunk-batch-size: ${RAG_CHUNK_BATCH_SIZE:1000}
