spring:
  mongodb:
    uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/reactive_rag?authSource=admin}

file-processor:
  dataset-path: ${DATASET_PATH:./data/dataset.txt}
  chunk-index: ${CHUNK_INDEX:0}
  start-byte-inclusive: ${START_BYTE_INCLUSIVE:0}
  end-byte-exclusive: ${END_BYTE_EXCLUSIVE:1048576}
  max-line-length-bytes: ${MAX_LINE_LENGTH_BYTES:1048576}
  buffer-size-bytes: ${BUFFER_SIZE_BYTES:65536}